### ISSUE TITLE
Could not find package apolon13/yii2-sftp-phpseclib

### ISSUE THREAD

**Issue by nagbhushan** [apolon13/yii2-sftp-phpseclib#1]
Hi,

I get below error when i try to install it.

[InvalidArgumentException]                                                   
  Could not find package apolon13/yii2-sftp-phpseclib at any version for your  
   minimum-stability (stable). Check the package spelling or your minimum-sta  
  bility   

Let me know how to fix it.....is it really a typo error....???

**Comment by apolon13** [comment]
Hi, try adding to your composer.json  "minimum-stability": "dev"

2017-01-11 15:31 GMT+03:00 nagbhushan <notifications@github.com>:

**Comment by nagbhushan** [comment]
Hey Thank you.

Will check in sometime.

**Comment by nagbhushan** [comment]
Yes that worked thank you.
